# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: build the go binary in dev mode and install
    deps:
      - clean
    cmds:
      - go build -o bin/sigex
      - go install
  clean:
    desc: clean the build directory
    cmds:
      - rm -rf bin
  example:
    desc: run the example node app
    cmds:
      - >
        sigex
        -f example_node/config/.dev.env
        -f example_node/.env
        node example_node/app.js
