# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: build the go binary in dev mode and install
    deps:
      - clean
    cmds:
      - go build -o bin/sigex
      - go install
  clean:
    desc: clean the build directory
    cmds:
      - rm -rf bin
  test:
    desc: run unit tests
    cmds:
      - go test -cover -v ./...
  example:
    desc: run the example node app
    cmds:
      - >
        sigex
        -f examples/node/config/.dev.env
        -f examples/node/.env
        -e CLI_VAR=SomeCLIVar
        node examples/node/app.js
