name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-and-upload:
    name: Build and Upload
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: >
          go build -v
          -ldflags "-X github.com/signaldevs/sigex/cmd.version=${{ github.ref_name }}"
          -o sigex${{ matrix.goos == 'windows' && '.exe' || '' }} .

      - name: Run tests
        run: go test -v ./...

      - uses: actions/upload-artifact@v4
        name: Upload ${{github.ref_name}} release binary (${{ matrix.goos }}-${{ matrix.goarch }})
        with:
          name: sigex-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./sigex${{ matrix.goos == 'windows' && '.exe' || '' }}

      - name: Package binary
        run: >
          tar -czvf sigex-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          sigex${{ matrix.goos == 'windows' && '.exe' || '' }}

      - name: Calculate SHA256 checksum
        run: >
          sha256sum sigex-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz > 
          sigex-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz.sha256.txt

      - name: Upload archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./sigex-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          asset_name: sigex-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./sigex-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz.sha256.txt
          asset_name: sigex-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz.sha256.txt
          asset_content_type: text/plain
